
name: base_N
description: BaseN encoding simular to base58 but using custom alphabet of any practical size
version: 0.0.1
author: Walnut Geek <wg@walnutgeek.com>
homepage: https://github.com/walnutgeek/base_n

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  crypto: ">=0.9.2 <3.0.0"
  collection: ">=1.2.0 <2.0.0"
  path: ^1.7.0

dev_dependencies:
  test: ">=0.12.0"